#!/usr/bin/python

# Copyright (c) 2016 SUSE LINUX GmbH, Nuernberg, Germany.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Triggers a jenkins job via the API
# Needed for job chains that are not possible to implement natively

import jenkins
import json
import os
import sys


def usage():
    print("Error: No job name defined as first parameter.\n" +
              "Add parameters as needed:\n" +
              "  jenkins-job-trigger <job_name> [ para1=val1 [ para2=val2 ]... ]")
    sys.exit(1)

def isSamePr (github_pr, buildinfo):    
    if "actions" not in buildinfo:
        return False

    for action in buildinfo["actions"]:
        if "_class" not in action or action["_class"] != "hudson.model.ParametersAction":
            continue
        if "parameters" not in action:
            continue
        for param in action["parameters"]:
            if "name" not in param:
                continue
            if param["name"] == "github_pr":
                if "value" not in param:
                    continue
                buildPRInfo = param["value"].split(":")
                otherPRInfo = github_pr.split(":")
                return ( 
                    buildPRInfo[0] == otherPRInfo[0] and  #org
                    buildPRInfo[1] == otherPRInfo[1] and  #repo
                    buildPRInfo[2] == otherPRInfo[2] and  #branch
                    buildPRInfo[3] == otherPRInfo[3]      #pr-nr
                )
    return False

def connect_to_server():
    config_files = ('/etc/jenkinsapi.conf', './jenkinsapi.conf')
    config = dict()

    for config_file in config_files:
        if not os.path.exists(config_file):
            continue
        with open(config_file, 'r') as f:
            config.update(json.load(f))

    if not config:
        print('Error: No config file could be loaded. Please create either of: %s' %
              ', '.join(config_files))
        sys.exit(1)

    return jenkins.Jenkins(str(config['jenkins_url']),
                             username=config['jenkins_user'],
                             password=config['jenkins_api_token'])


def jenkins_build_job(job_name, job_args=[]):
    if not job_name:
        usage()

    job_parameters = dict()

    github_pr = None

    for param in job_args:
        # backwards compatibility, ignore -p and -m
        if param in ('-p', '-m'):
            continue
        p_key, _, p_val = param.partition('=')
        job_parameters[p_key.strip(' ')] = p_val.strip(' ')

        if p_key == "github_pr":
            github_pr = p_val

    server = connect_to_server()

    #this is a github_pr, lets make sure no others are running before we trigger it again
    if github_pr != None:
        #stop all queued builds:
        queued = server.get_queue_info()
        for build in queued:
            if "task" not in build or "name" not in build["task"]:
                continue
            if build["task"]["name"] != job_name:
                continue
            if isSamePr(github_pr, build):
                print("Found PR in queue, cancelling")
                server.cancel_queue(build["id"])

        running_builds = server.get_running_builds()
        for build in running_builds:
            if "name" in build and build["name"] == job_name:
                print("Found running job")
                bi = server.get_build_info(build["name"], build["number"])
                if isSamePr(github_pr, bi):
                    print("Stopping build: {}".format(build["number"]))
                    server.stop_build(build["name"], build["number"])

    server.build_job(job_name, job_parameters)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        usage()
    args = list()
    if len(sys.argv) > 2:
        args.extend(sys.argv[2:])
    jenkins_build_job(sys.argv[1], args)
